version: "3.9"
services:
  cloud-config:
    container_name: cloud-config
    image: 611622/ims-cloud-config
    expose:
      - 9296
    networks:
      - csl-ims

networks:
  csl-ims:
    driver: bridge
