version: '3.7'
services:
  ims-mysql:
    container_name: ims-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ims
      MYSQL_ROOT_PASSWORD: Times@12345
    volumes:
      - ./ims-mysql:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always
