version: "3.9"
services:
  cloud-config:
    container_name: cloud-config
    image: 611622/ims-cloud
    networks:
      - csl-ims

  customer-service:
    container_name: customer-service
    image: 611622/ims-customer-service
    networks:
      - csl-ims
    depends_on:
      - cloud-config

  gateway:
    container_name: gateway
    image: 611622/ims-gateway
    ports:
    - 8080:8080
    networks:
      - csl-ims

  product-service:
    container_name: product-service
    image: 611622/ims-product-service
    networks:
      - csl-ims
    depends_on:
      - cloud-config

  service-registry:
    container_name: service-registry
    image: 611622/ims-service-registry
    networks:
      - csl-ims

  supplier-service:
    container_name: supplier-service
    image: 611622/ims-supplier-service
    networks:
      - csl-ims
    depends_on:
      - cloud-config

  user-service:
    container_name: user-service
    image: 611622/ims-user-service
    networks:
      - csl-ims
    depends_on:
      - cloud-config

networks:
  csl-ims: