version: "3.9"
services:
#  cloud-config:
#    container_name: cloud-config
#    image: 611622/ims-cloud-config
#    expose:
#      - 9296
#    networks:
#      - csl-ims

  customer-service:
    container_name: customer-service
    image: 611622/ims-customer-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://cloud-config:9296"}}}}'
    expose:
      - 9001
    networks:
      - csl-ims

  gateway:
    container_name: gateway
    image: 611622/ims-gateway
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - csl-ims

  product-service:
    container_name: product-service
    image: 611622/ims-product-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://cloud-config:9296"}}}}'
    expose:
      - 9002
    networks:
      - csl-ims

  service-registry:
    container_name: service-registry
    image: 611622/ims-service-registry
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://cloud-config:9296"}}}}'
    expose:
      - 8761
    networks:
      - csl-ims

  supplier-service:
    container_name: supplier-service
    image: 611622/ims-supplier-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://cloud-config:9296"}}}}'
    expose:
      - 9003
    networks:
      - csl-ims

  user-service:
    container_name: user-service
    image: 611622/ims-user-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://cloud-config:9296"}}}}'
    expose:
      - 9004
    networks:
      - csl-ims

networks:
  csl-ims:
    driver: bridge
