server:
  port: 9001

spring:
  application:
    name: IMS-CUSTOMER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    hostname: ${EUREKA_SERVER:localhost}