spring:
  application:
    name: IMS-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ims-customer-service
          uri: lb://IMS-CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**

        - id: ims-product-service
          uri: lb://IMS-PRODUCT-SERVICE
          predicates:
            - Path=/products/**

        - id: ims-supplier-service
          uri: lb://IMS-SUPPLIER-SERVICE
          predicates:
            - Path=/supplier/**
          filters:
            - AuthenticationFilter

        - id: ims-user-service
          uri: lb://IMS-USER-SERVICE
          predicates:
            - Path=/users/**
            - Path=/auth/**
          filters:
            - AuthenticationFilter
