spring:
  application:
    name: IMS-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      routes:
        - id: IMS-CUSTOMER-SERVICE
          uri: lb://IMS-CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**, /v3/api-docs/IMS-CUSTOMER

        - id: IMS-PRODUCT-SERVICE
          uri: lb://IMS-PRODUCT-SERVICE
          predicates:
            - Path=/products/**, /categories/**, /v3/api-docs/IMS-PRODUCT

        - id: IMS-SUPPLIER-SERVICE
          uri: lb://IMS-SUPPLIER-SERVICE
          predicates:
            - Path=/supplier/**, /v3/api-docs/IMS-SUPPLIER

        - id: IMS-USER-SERVICE
          uri: lb://IMS-USER-SERVICE
          predicates:
            - Path=/auth/**, /users/**, /v3/api-docs/IMS-USER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    hostname: ${EUREKA_SERVER:localhost}