spring:
  application:
    name: IMS-GATEWAY
  cloud:
    gateway:
      routes:
        - id: IMS-CUSTOMER-SERVICE
          uri: lb://IMS-CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**

        - id: IMS-PRODUCT-SERVICE
          uri: lb://IMS-PRODUCT-SERVICE
          predicates:
            - Path=/products/**

        - id: IMS-SUPPLIER-SERVICE
          uri: lb://IMS-SUPPLIER-SERVICE
          predicates:
            - Path=/supplier/**

        - id: IMS-USER-SERVICE
          uri: http://localhost:9004
          predicates:
            - Path=/auth/**, /users/**
