server:
  port: 9002

spring:
  application:
    name: IMS-PRODUCT-SERVICE

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic