server:
  port: 9001

spring:
  application:
    name: IMS-USER-SERVICE
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  jwt:
    secret: ${JWT_SECRET:cslimsb4devops2023DhakaBangladeshGHNJHHHGAihasbhjakuuysSKmSNNansnaya7712638827491731735478136713564781313731341GGHhbVGfsarFRE}