server:
  servlet:
    context-path: /customers
  port: 9004

spring:
  application:
    name: IMS-USER-SERVICE

app:
  jwt:
    secret: ${JWT_SECRET:cslimsb4devops2023DhakaBangladeshGHNJHHHGAihasbhjakuuysSKmSNNansnaya7712638827491731735478136713564781313731341GGHhbVGfsarFRE}